[build]
  # Build command
  command = "npm run build"
  # Directory to publish
  publish = "build"

[build.environment]
  # Node version for build
  NODE_VERSION = "18"

# Redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache service worker
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"
