const fs = require('fs');
const cheerio = require('cheerio');

async function scrapeAllArticles() {
  let allArticles = [];
  let page = 1;
  let hasMore = true;
  let idCounter = 1;

  while (hasMore) {
    const url = page === 1 
      ? 'https://smartliving.ro/author/oana-tenea/' 
      : `https://smartliving.ro/author/oana-tenea/page/${page}/`;
      
    console.log(`Scraping ${url}...`);
    try {
      const response = await fetch(url, {
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
          'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8',
          'Accept-Language': 'en-US,en;q=0.9,ro;q=0.8',
        }
      });
      
      if (response.status === 404) {
        console.log('No more pages found (404).');
        hasMore = false;
        break;
      }
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      
      const html = await response.text();
      const $ = cheerio.load(html);
      
      // Let's check what articles looks like in the content
      const articles = $('article, .wp-block-post, li.wp-block-post');
      
      if (articles.length === 0) {
        console.log('No articles found on this page.');
        hasMore = false;
        break;
      }

      articles.each((i, element) => {
        const titleEl = $(element).find('h3.sl-card__title').first();
        if (titleEl.length === 0) return; // not a real article card
        
        const title = titleEl.text().trim();
        const hrefEl = $(element).find('a.sl-card').first();
        const href = hrefEl.attr('href');
        
        const excerptEl = $(element).find('.sl-card__excerpt').first();
        const excerpt = excerptEl.text().trim();
        
        const categoryEl = $(element).find('.sl-eyebrow').first();
        const category = categoryEl.text().trim() || 'Psihologie';

        // date logic 
        const dateEl = $(element).find('.sl-card__date, time').first();
        let publishDate = '2024-01-01'; // Default date
        if (dateEl.length > 0) {
           const ds = dateEl.attr('datetime') || dateEl.text().trim();
           // Attempt naive parse
           publishDate = ds;
        }

        // Just generate a decreasing date if we can't parse easily
        // since the array is sorted, we can just use 2025-01-15 minus idCounter days
        let d = new Date('2025-01-15');
        d.setDate(d.getDate() - idCounter * 7); // minus a week for each article roughly
        publishDate = d.toISOString().split('T')[0];

        // Estimate reading time
        const readingTime = Math.max(3, Math.ceil(excerpt.length / 50));
        
        const tagKeywords = {
          'anxietate': 'Anxietate', 'relații': 'Relații', 'cuplu': 'Cuplu',
          'stress': 'Stress', 'emoții': 'Emoții', 'comunicare': 'Comunicare',
          'copii': 'Parentaj', 'părinți': 'Parentaj', 'depresie': 'Depresie',
          'autoestim': 'Autoestimă', 'încredere': 'Încredere', 'vindecare': 'Vindecare',
          'trauma': 'Trauma'
        };
        
        const tags = [];
        for (const [kw, tag] of Object.entries(tagKeywords)) {
          if ((title + ' ' + excerpt).toLowerCase().includes(kw)) {
             tags.push(tag);
          }
        }
        if (tags.length === 0) tags.push(category);

        allArticles.push({
          id: `sl-${idCounter++}`,
          title,
          excerpt: excerpt.substring(0, 200) + (excerpt.length > 200 ? '...' : ''),
          category: category,
          readingTime: readingTime,
          publishDate: publishDate,
          externalUrl: href,
          tags: tags.slice(0, 3),
          source: 'SmartLiving.ro'
        });
      });
      
      console.log(`Page ${page}: found ${allArticles.length} total so far.`);
      page++;
      
      // Safety limit
      if (page > 10) hasMore = false;
    } catch (error) {
      console.error('Error fetching page:', error);
      hasMore = false;
    }
  }

  console.log(`Found a total of ${allArticles.length} articles.`);

  // Write to src/data/smartLivingArticles.js
  const fileContent = `// Articles published on SmartLiving.ro by Oana Tenea\n// Auto-generated by scraper\n\nexport const smartLivingArticles = ${JSON.stringify(allArticles, null, 2)};\n\n// Working hours\nexport const workingHours = {\n  schedule: {\n    monday: { start: '09:00', end: '18:00', available: true },\n    tuesday: { start: '09:00', end: '18:00', available: true },\n    wednesday: { start: '09:00', end: '18:00', available: true },\n    thursday: { start: '09:00', end: '18:00', available: true },\n    friday: { start: '', end: '', available: false },\n    saturday: { start: '', end: '', available: false },\n    sunday: { start: '', end: '', available: false }\n  },\n  note: 'Programările se fac prin telefon sau email. În situații de urgență, vă rog să contactați serviciile de urgență medicală.',\n  emergencyNote: 'Pentru situații de criză psihologică, apelați 0800 080 200 (Telefonul Speranței) disponibil 24/7.'\n};\n`;

  fs.writeFileSync('c:/Dev/oanapsy/src/data/smartLivingArticles.js', fileContent);
  console.log('Saved to src/data/smartLivingArticles.js');
}

scrapeAllArticles();
